### ISSUE TITLE
При рестарте сохраняются жизни

### ISSUE THREAD

**Issue by live-HOCOK** [IlushkaXXX/Game#112]
При проигрыше отбрасывается на последнюю волну с сохранением жизни.. сделать так что бы кидало на первую волну жизни были полные..

**Comment by live-HOCOK** [comment]
@IlushkaXXX  нужно ли сохранять пончики?

**Comment by IlushkaXXX** [comment]
@live-HOCOK  так и не вкурил что ты хочешь туту сделать, вроде решили что сохраняем чекпоинты и потом загружаемся при старте?

**Comment by live-HOCOK** [comment]
оставим пока так, дальше посмотрим как пойдет
