### ISSUE TITLE
Нужен фон во все сцены

### ISSUE THREAD

**Issue by IlushkaXXX** [IlushkaXXX/Game#16]

**Comment by live-HOCOK** [comment]
@IlushkaXXX фон какой? в интерфейсе или фон игры?

**Comment by IlushkaXXX** [comment]
Думаю что основной фон игры не сильно должен отличаться от фона в интерфейс=е

**Comment by live-HOCOK** [comment]
смотря какой сеттинг будет, от этого и будет плясать фон. Мне кажется, что рано пока делать этот таск

**Comment by IlushkaXXX** [comment]
тогда оставим пока залиивку

**Comment by live-HOCOK** [comment]
да, сейчас просто одноцветный фон.. после выполнения #17 можно уже думать

**Comment by IlushkaXXX** [comment]
Думаю нужно добавить нормальный космический фон с движением

**Comment by live-HOCOK** [comment]
done
