### ISSUE TITLE
Вести подсчет собранных монет

### ISSUE THREAD

**Issue by live-HOCOK** [IlushkaXXX/Game#27]
1. выводить как элемент интерфейса во время игры. Оно же будет кнопкой перехода в магазин.
2. выводить в главном меню количество собранных монет, если в игру до этого играли

**Comment by IlushkaXXX** [comment]
@live-HOCOK  может оставим пончики?)

**Comment by IlushkaXXX** [comment]
магазина пока нет

**Comment by live-HOCOK** [comment]
done
