### ISSUE TITLE
Иконки оружия и выбор при нажатии на иконку

### ISSUE THREAD

**Issue by IlushkaXXX** [IlushkaXXX/Game#92]
Возле звезды реализовать иконки пушек при нажатии на которую будет меняться текущая пушка. Текущая выбранная иконка пропадает из списка.

**Comment by IlushkaXXX** [comment]
Нужен фон для  иконок

**Comment by live-HOCOK** [comment]
нужно поднять землю.. см. https://drive.google.com/open?id=15vJt71NHfPytDrkbYKk4vYiu8ztbqQjd

**Comment by live-HOCOK** [comment]
done
